var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
export var Container = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    padding: 0 25px 50px 25px;\n\n    @media (max-width: 450px) {\n        padding: 0 10px 40px 10px;\n    }\n"], ["\n    padding: 0 25px 50px 25px;\n\n    @media (max-width: 450px) {\n        padding: 0 10px 40px 10px;\n    }\n"])));
export var PhotoInput = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    display: flex;\n    align-items: center;\n\n    position: relative;\n\n    width: 90px;\n    height: 90px;\n\n    border-radius: 50%;\n\n    background-color: #c0c0c0;\n\n    overflow: hidden;\n\n    input {\n        position: absolute;\n        top: 0;\n        left: 0;\n\n        width: 100%;\n        height: 100%;\n        \n        border: none;\n\n        opacity: 0;\n        z-index: 10;\n\n        cursor: pointer;\n    }\n\n    img {\n        width: 100%;\n        height: 100%;\n        object-fit: cover;\n    }\n"], ["\n    display: flex;\n    align-items: center;\n\n    position: relative;\n\n    width: 90px;\n    height: 90px;\n\n    border-radius: 50%;\n\n    background-color: #c0c0c0;\n\n    overflow: hidden;\n\n    input {\n        position: absolute;\n        top: 0;\n        left: 0;\n\n        width: 100%;\n        height: 100%;\n        \n        border: none;\n\n        opacity: 0;\n        z-index: 10;\n\n        cursor: pointer;\n    }\n\n    img {\n        width: 100%;\n        height: 100%;\n        object-fit: cover;\n    }\n"])));
export var InputPassword = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    position: relative;\n\n    input {\n        width: 100%;\n        padding-right: 35px;\n    }\n\n    img {\n        position: absolute;\n        right: 10px;\n\n        width: 15px;\n        height: fit-content;\n\n        cursor: pointer;\n    }\n"], ["\n    position: relative;\n\n    input {\n        width: 100%;\n        padding-right: 35px;\n    }\n\n    img {\n        position: absolute;\n        right: 10px;\n\n        width: 15px;\n        height: fit-content;\n\n        cursor: pointer;\n    }\n"])));
var templateObject_1, templateObject_2, templateObject_3;
