var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
export var Container = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    width: 100%;\n    max-width: 590px;\n    \n    min-height: 100vh;\n\n    padding: 15px;\n    padding-top: 25px;\n    margin: 0 auto;\n\n    padding-bottom: 50px;\n"], ["\n    width: 100%;\n    max-width: 590px;\n    \n    min-height: 100vh;\n\n    padding: 15px;\n    padding-top: 25px;\n    margin: 0 auto;\n\n    padding-bottom: 50px;\n"])));
export var Header = styled.header(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    display: flex;\n    justify-content: space-between;\n\n    img {\n        cursor: pointer;\n    }\n\n    .photoPerfil {\n        width: 30px;\n        height: 30px;\n        object-fit: cover;\n\n        border-radius: 50%;\n\n        background-color: #f0f0f0;\n\n        cursor: pointer;\n    }\n"], ["\n    display: flex;\n    justify-content: space-between;\n\n    img {\n        cursor: pointer;\n    }\n\n    .photoPerfil {\n        width: 30px;\n        height: 30px;\n        object-fit: cover;\n\n        border-radius: 50%;\n\n        background-color: #f0f0f0;\n\n        cursor: pointer;\n    }\n"])));
export var ContainerContent = styled.section(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    width: fit-content;\n    padding: 15px;\n    margin: 0 auto;\n    margin-top: 30px;\n\n    border-radius: 15px;\n\n    box-shadow: 0 0 25px #18181840;\n    background-color: var(--semiDarkNavy);\n\n    h1 {\n        margin-bottom: 30px;\n\n        text-transform: uppercase;\n        color: var(--silver);\n    }\n\n    button {\n        width: 100%;\n\n        border-width: 0px;\n    }\n\n"], ["\n    width: fit-content;\n    padding: 15px;\n    margin: 0 auto;\n    margin-top: 30px;\n\n    border-radius: 15px;\n\n    box-shadow: 0 0 25px #18181840;\n    background-color: var(--semiDarkNavy);\n\n    h1 {\n        margin-bottom: 30px;\n\n        text-transform: uppercase;\n        color: var(--silver);\n    }\n\n    button {\n        width: 100%;\n\n        border-width: 0px;\n    }\n\n"])));
export var LoadingImg = styled.img(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    @keyframes loading {\n        0% {\n            rotate: 0deg;\n        }\n\n        100% {\n            rotate: 365deg;\n        }\n    }\n\n\n    height: 16px;\n    animation: loading 1s infinite;\n    \n\n"], ["\n    @keyframes loading {\n        0% {\n            rotate: 0deg;\n        }\n\n        100% {\n            rotate: 365deg;\n        }\n    }\n\n\n    height: 16px;\n    animation: loading 1s infinite;\n    \n\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
