var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
export var Container = styled.section(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    display: flex;\n    flex-direction: column;\n    align-items: center;\n    justify-content: center;\n\n    width: 100%;\n    height: 100%;\n    min-height: 100vh;\n\n    color: var(--silver);\n\n    article {\n        width: 100%;\n        max-width: 480px;\n\n        display: grid;\n        grid-template-columns: 1fr;\n        grid-gap: 30px;\n\n        padding: 30px 20px;\n\n        border-radius: 15px;\n\n        text-align: center;\n\n        background-color: var(--semiDarkNavy);\n        box-shadow: 0 0 25px #18181840;\n\n    }\n\n    h1 {\n        font-size: 4rem;\n        line-height: 3.4rem;\n    }\n\n    p {\n        font-size: 1.2rem;\n    }\n"], ["\n    display: flex;\n    flex-direction: column;\n    align-items: center;\n    justify-content: center;\n\n    width: 100%;\n    height: 100%;\n    min-height: 100vh;\n\n    color: var(--silver);\n\n    article {\n        width: 100%;\n        max-width: 480px;\n\n        display: grid;\n        grid-template-columns: 1fr;\n        grid-gap: 30px;\n\n        padding: 30px 20px;\n\n        border-radius: 15px;\n\n        text-align: center;\n\n        background-color: var(--semiDarkNavy);\n        box-shadow: 0 0 25px #18181840;\n\n    }\n\n    h1 {\n        font-size: 4rem;\n        line-height: 3.4rem;\n    }\n\n    p {\n        font-size: 1.2rem;\n    }\n"])));
export var BtnBackPage = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    width: 100%;\n    max-width: 480px;\n\n    margin-bottom: 15px;\n\n    span {\n        padding: 0 14px;\n        font-size: 1.2rem;\n\n        cursor: pointer;\n        position: relative;\n\n        &::after {\n            content: \"\";\n            position: absolute;\n            top: calc(100% + 5px);\n            left: 50%;\n\n            height: 1px;\n            width: 0%;\n\n            background-color: var(--silver);\n\n            transition: all .2s ease;\n        }\n\n        &:hover::after {\n            left: 0;\n            width: 100%;\n        }\n    }\n"], ["\n    width: 100%;\n    max-width: 480px;\n\n    margin-bottom: 15px;\n\n    span {\n        padding: 0 14px;\n        font-size: 1.2rem;\n\n        cursor: pointer;\n        position: relative;\n\n        &::after {\n            content: \"\";\n            position: absolute;\n            top: calc(100% + 5px);\n            left: 50%;\n\n            height: 1px;\n            width: 0%;\n\n            background-color: var(--silver);\n\n            transition: all .2s ease;\n        }\n\n        &:hover::after {\n            left: 0;\n            width: 100%;\n        }\n    }\n"])));
export var Timer = styled.div(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    /* background-color: red; */\n    margin: 0;\n\n    p {\n        width: fit-content;\n        /* background-color: blue; */\n    }\n"], ["\n    /* background-color: red; */\n    margin: 0;\n\n    p {\n        width: fit-content;\n        /* background-color: blue; */\n    }\n"])));
export var InputPassword = styled.div(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n\n    display: flex;\n    /* justify-content: center; */\n    align-items: center;\n    \n    position: relative;\n\n    input {\n        /* position: absolute; */\n        width: 100%;\n    }\n\n    img {\n        position: absolute;\n        right: 12px;\n        \n        width: 15px;\n        cursor: pointer;\n    }\n"], ["\n\n    display: flex;\n    /* justify-content: center; */\n    align-items: center;\n    \n    position: relative;\n\n    input {\n        /* position: absolute; */\n        width: 100%;\n    }\n\n    img {\n        position: absolute;\n        right: 12px;\n        \n        width: 15px;\n        cursor: pointer;\n    }\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
