var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
import styled from "styled-components";
export var Container = styled.div(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n    width: 100%;\n    max-width: 1200px;\n\n    margin: 0 auto;\n    padding: 0 20px;\n\n    @media (max-width: 450px) {\n        padding: 0 12px 20px 10px;\n    }\n"], ["\n    width: 100%;\n    max-width: 1200px;\n\n    margin: 0 auto;\n    padding: 0 20px;\n\n    @media (max-width: 450px) {\n        padding: 0 12px 20px 10px;\n    }\n"])));
export var ContainerAudio = styled.div(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n    width: 100%;\n    max-width: 400px;\n\n    margin: 18px auto 0 auto;\n    \n"], ["\n    width: 100%;\n    max-width: 400px;\n\n    margin: 18px auto 0 auto;\n    \n"])));
export var Header = styled.header(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    display: flex;\n    justify-content: right;\n    \n    width: 100%;\n    padding: 14px 0;\n\n    ul {\n        display: flex;\n        flex-direction: row;\n        text-transform: uppercase;\n\n        color: var(--silver);\n    }\n\n    li {\n        position: relative;\n\n        padding: 0 5px;\n\n        transition: color .14s ease;\n        cursor: pointer;\n\n        &::after {\n            content: \"\";\n            position: absolute;\n            left: 50%;\n            top: calc(100% + 2px);\n\n            height: 1px;\n            width: 0;\n\n            background-color: var(--silver);\n            transition: all .14s ease;\n        }\n\n        &:hover {\n            color: var(--silverHover);\n\n            &::after {\n                left: 0;\n                width: 100%;\n            }\n        }\n    }\n"], ["\n    display: flex;\n    justify-content: right;\n    \n    width: 100%;\n    padding: 14px 0;\n\n    ul {\n        display: flex;\n        flex-direction: row;\n        text-transform: uppercase;\n\n        color: var(--silver);\n    }\n\n    li {\n        position: relative;\n\n        padding: 0 5px;\n\n        transition: color .14s ease;\n        cursor: pointer;\n\n        &::after {\n            content: \"\";\n            position: absolute;\n            left: 50%;\n            top: calc(100% + 2px);\n\n            height: 1px;\n            width: 0;\n\n            background-color: var(--silver);\n            transition: all .14s ease;\n        }\n\n        &:hover {\n            color: var(--silverHover);\n\n            &::after {\n                left: 0;\n                width: 100%;\n            }\n        }\n    }\n"])));
export var Section = styled.section(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    width: 100%;\n    max-width: 400px;\n\n    margin: 40px auto 0 auto;\n    padding: 30px 30px 25px 30px;\n\n    display: flex;\n    flex-direction: column;\n    align-items: center;\n\n    background-color: var(--semiDarkNavy);\n    border-radius: 15px;\n\n    box-shadow: 0 0 25px #18181840;\n\n    h1 {\n        margin-bottom: 30px;\n\n        text-transform: uppercase;\n        color: var(--silver);\n    }\n\n    ul {\n        display: flex;\n        flex-direction: column;\n        align-items: center;\n    }\n\n    button {\n        width: 100%;\n        margin-bottom: 15px;\n    }\n\n\n    @media (max-width: 450px) {\n        padding: 30px 15px 20px 15px;\n    }\n\n"], ["\n    width: 100%;\n    max-width: 400px;\n\n    margin: 40px auto 0 auto;\n    padding: 30px 30px 25px 30px;\n\n    display: flex;\n    flex-direction: column;\n    align-items: center;\n\n    background-color: var(--semiDarkNavy);\n    border-radius: 15px;\n\n    box-shadow: 0 0 25px #18181840;\n\n    h1 {\n        margin-bottom: 30px;\n\n        text-transform: uppercase;\n        color: var(--silver);\n    }\n\n    ul {\n        display: flex;\n        flex-direction: column;\n        align-items: center;\n    }\n\n    button {\n        width: 100%;\n        margin-bottom: 15px;\n    }\n\n\n    @media (max-width: 450px) {\n        padding: 30px 15px 20px 15px;\n    }\n\n"])));
var templateObject_1, templateObject_2, templateObject_3, templateObject_4;
